### ISSUE TITLE
Instances of colcon not terminating on windows

### ISSUE THREAD

**Issue by sloretz** [colcon/colcon-core#157] opened 2019-01-18 19:26 UTC
ros2/build_cop#161 describes nightly failures that happened due to being unable to delete the workspace. This is caused by an old colcon process that did not terminate,

There are two colcon processes on windows_portable that appear to be running long beyond what they should. Neither is using a much CPU ( < 1% ). Both have a log file open that blocked deleting the workspace in a subsequent job.

<details><summary>pip freeze</summary>

```
atomicwrites==1.1.5
attrs==18.1.0
catkin-pkg==0.4.10
colcon-cmake==0.2.5
colcon-core==0.3.15
colcon-defaults==0.2.1
colcon-library-path==0.2.1
colcon-metadata==0.2.1
colcon-output==0.2.3
colcon-package-information==0.2.2
colcon-package-selection==0.2.3
colcon-parallel-executor==0.2.3
colcon-pkg-config==0.1.0
colcon-powershell==0.3.3
colcon-python-setup-py==0.2.1
colcon-recursive-crawl==0.2.0
colcon-ros==0.3.6
colcon-test-result==0.3.1
colorama==0.3.9
coloredlogs==10.0
coverage==4.5.2
distlib==0.2.8
docutils==0.14
empy==3.3.2
flake8==3.6.0
flake8-blind-except==0.1.1
flake8-builtins==1.4.1
flake8-class-newline==1.6.0
flake8-comprehensions==1.4.1
flake8-deprecated==1.3
flake8-docstrings==1.3.0
flake8-import-order==0.18
flake8-polyfill==1.0.2
flake8-quotes==1.0.0
humanfriendly==4.13
lark-parser==0.6.5
mccabe==0.6.1
mock==2.0.0
more-itertools==4.2.0
nose==1.3.7
pbr==4.1.0
pep8==1.7.1
pluggy==0.7.1
py==1.5.4
pycodestyle==2.4.0
pydocstyle==3.0.0
pydot==1.4.0
pyflakes==2.0.0
pyparsing==2.3.1
PyQt5==5.11.3
PyQt5-sip==4.19.13
pyreadline==2.1
pytest==4.1.1
pytest-cov==2.6.1
pytest-repeat==0.7.0
pytest-rerunfailures==6.0
pytest-runner==4.2
python-dateutil==2.7.3
PyYAML==3.13
six==1.11.0
snowballstemmer==1.2.1
vcstool==0.1.38
```
</details>
<details><summary>First colcon process</summary>
Working directory

```
C:\J\workspace\nightly_win_deb\ws\
```

Command line

```
"c:\python37\python_d.exe"  "C:\Python37\Scripts\colcon.exe" build --base-paths "src" --build-base "build" --install-base "install" --merge-install --event-handlers console_cohesion+ console_package_list+ --cmake-args -DBUILD_TESTING=ON --no-warn-unused-cli -DCMAKE_BUILD_TYPE=Debug -DINSTALL_EXAMPLES=OFF -DSECURITY=ON
```

Open file which caused CI jobs to fail

```
C:\J\workspace\nightly_win_deb\ws\log\build_2019-01-15_23-32-01\logger_all.log
```
</details>
<details><summary>Second colcon process</summary>
Working directory

```
C:\J\workspace\nightly_win_extra_rmw_rel\ws\
```

Command line

```
"c:\python37\python.exe"  "C:\Python37\Scripts\colcon.exe" build --base-paths "src" --build-base "build" --install-base "install" --merge-install --event-handlers console_cohesion+ console_package_list+ --cmake-args -DBUILD_TESTING=ON --no-warn-unused-cli -DCMAKE_BUILD_TYPE=Release -DINSTALL_EXAMPLES=OFF -DSECURITY=ON
```

Open file which caused CI jobs to fail

```
Open file to C:\J\workspace\nightly_win_extra_rmw_rel\ws\log\build_2019-01-15_23-57-45\logger_all.log
```
</details>

[nightly_win_deb__logger_all.log](https://github.com/colcon/colcon-core/files/2774540/nightly_win_deb__logger_all.log)
[nightly_win_extra_rmw_rel__logger_all.log](https://github.com/colcon/colcon-core/files/2774254/nightly_win_extra_rmw_rel__logger_all.log)

**Comment by dirk-thomas** [comment] 2019-01-18 19:33
Were any of the previous builds aborted or exited in a non-clean way? If yes, this might be related to #58.

Anyway it will likely require a reproducible example in order to be investigated.

**Comment by sloretz** [comment] 2019-01-18 19:37
> Were any of the previous builds aborted or exited in a non-clean way? If yes, this might be related to #58.

I don't think so, no aborted builds show up in https://ci.ros2.org/computer/windows_portable/builds

**Comment by sloretz** [comment] 2019-01-18 21:07
> I can see that nothing actually stops the colcon process and since the new build started only minutes after the previous build ended it is pretty likely that the invocation hadn't finished yet.

Looking at all the builds, https://ci.ros2.org/job/nightly_win_deb/1129/ failed to delete the workspace Jan 18, 2019 7:30:00 AM.
 The previous job of that type on the came machine was https://ci.ros2.org/job/nightly_win_deb/1127/ started at Jan 16, 2019 7:47:32 AM which also failed to delete the workspace. The job before that died with a java traceback https://ci.ros2.org/job/nightly_win_deb/1126/console and was started Jan 16, 2019 7:30:00 AM . I think 1126 created the colcon process since the file that could be deleted was in a directory called `build_2019-01-15_23-32-01`. That process was still running a couple hours ago, and I manually killed it. 2 to 3 days seems too long for it to be that the colcon invocation hadn't finished.

**Comment by dirk-thomas** [comment] 2019-01-18 21:12
It would be good to attach the content of the log directory of the still running build. That will allow to investigate what state that invocation was in.

**Comment by sloretz** [comment] 2019-01-18 21:15
The only thing left in the directory was the log file that was locked. Maybe the jobs after deleted everything but the locked log file? The log files are attached to the issue.

**Comment by dirk-thomas** [comment] 2019-01-18 21:53
The relevant lines of the text log are the following:

<details>

```
[1431.249s] Invoking command in 'build\test_msgs': cmake.EXE --build build\test_msgs --config Release
[1625.309s] Invoking command in 'build\geometry_msgs': cmake.EXE --build build\geometry_msgs --config Release
[1680.608s] run_until_complete was interrupted
[1680.608s] run_until_complete again
[1680.795s] Invoked command in 'build\geometry_msgs' returned '3221225786': cmake.EXE --build build\geometry_msgs --config Release
```

</details>

To summarize in "text" form:
* `cmake --build` is invoked on for `geometry_msgs` and `test_msgs`
* A `SIGINT` was received and the build of `geometry_msgs` exited with an error code
* The build of `test_msgs` never exited

Only the event log (which we don't have) would provide enough information to reason about the internal state of the executor and the pending tasks.

**Comment by dirk-thomas** [comment] 2019-01-22 18:20
I will go ahead and close this as a duplicate of #58.

**Closed by dirk-thomas** 2019-01-22 18:20 UTC
Labels: bug
