### ISSUE TITLE
symlink-install only creates symlinks in the build folder NOT the install folder, why?

### ISSUE THREAD

**Issue by TheConstructAi** [colcon/colcon-core#482] opened 2022-02-10 10:14 UTC
Hi to reproduce this issue:

```
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws/src
git clone https://bitbucket.org/theconstructcore/ros2_build_tests.git
cd ~/ros2_ws
source /opt/ros/galactic/setup.bash
colcon build --symlink-install
source install/setup.bash
ros2 run build_test_pkg script1_exe
```

**Expected behavior**

I would expect that the symlinks are inside the install folder which is the one form where we use the files

**Actual behavior**

It's sourcing the build folder, which I don't understand its use then

this example uses a yaml file from the install path, and no matter what you do, you need to compile to update those changes, because the file used is the one in the **install** folder.

Is this intended to work like this? what is the advantage then of using symlink apart from the fact of not having to compile when we only change python scripts?

And even this it's not clear how this is accomplished, where are the symlinks in the install folder to be able to use the source version of the python scripts without compiling again?

I think this is a recurring question and it's really confusing for users.

**Comment by cottsay** [comment] 2022-05-05 19:53
This behavior is supported by the underlying build system and isn't implemented by `colcon` directly.

For example, here is where `colcon` tells `ament_cmake` packages to symlink install: https://github.com/colcon/colcon-ros/blob/d7a66047e5aac95ee31eee2ef837f76919e2be9e/colcon_ros/task/ament_cmake/build.py#L50-L53

The symlink installation for Python packages [is more complex](https://github.com/colcon/colcon-core/blob/3727e62389511c9456a35ed104998d084e280ba0/colcon_core/task/python/build.py#L35) and relies on the `develop` verb. In truth, the source code for your example `build_test_pkg` package uses an "egg-link" file to the package subdirectory in `build`, so changing the sources will affect the installed environment as you desire. Unfortunately, the `data_files` specified in your `setup.py` don't get symlinked by Python. The fact that they're using a non-symlink-based system (egg-link) to take care of linking the Python code makes me wonder if the lack of cross-platform symlink support is one reason that it isn't done for `data_files`.

**Comment by Usimian** [comment] 2022-09-02 13:53
Thanks for the explanation.
Is there a fix?

**Comment by vanem** [comment] 2023-03-15 09:08
This is confusing and inconsistent: the launch files  declared with CMakeLists.txt  install directives ARE symlinked in the install share folder!

**Comment by HomeworldL** [comment] 2023-04-19 15:05
I've encountered this problem as well. I need to use `colcon build` to recompile to update my changes (like `.launch` files). All the links are in the build folder. An inelegant way is to manually copy the links in the `build` to the `install`, but that is somewhat bothersome. Is there a better solution now?

**Comment by RodBelaFarin** [comment] 2023-11-23 19:18
Any news on this? It is still not working as expected.

**Comment by cottsay** [comment] 2023-11-24 00:00
I think this issue is mostly a duplicate of #169. There is discussion there of a possible solution. If you'd like to see that solution merged, please test it and provide feedback.

**Closed** 2024-02-06 02:27 UTC
