### ISSUE TITLE
Warn when building outside of workspace root

### ISSUE THREAD

**Issue by SebastianGrans** [colcon/colcon-core#366] opened 2020-07-29 09:42 UTC
I'm relatively new to ROS and I sometime find myself accidentally running `colcon build` in the wrong folder, i.e. not in the worspace root folder. This leads to `build`, `log`, and `install` folders in the wrong locations.   

I have two ideas on how this could be resolved: 

1. Warn and abort the build
2. Notify, but automatically build in the root folder

Either feature would also require some kind of `force` flag.
What do you think of this?

**Comment by dirk-thomas** [comment] 2020-07-29 15:20
Duplicate of #139.

**Closed by dirk-thomas** 2020-07-29 15:20 UTC
Labels: duplicate

**Comment by SebastianGrans** [comment] 2020-07-30 08:13
It seems like I need to hone my searching abilities. Thanks!
