### ISSUE TITLE
Confusing interaction between --base-paths and --paths

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#274] opened 2019-12-03 00:40 UTC
When searching for one package by path using `colcon info --paths /path/to/package`, colcon performed recursive package discovery. This seems to be because I set my `base-paths` in the defaults yaml file. Passing `--base-path "."` makes colcon only discover the package as specified.

defaults.yaml:
```
...
info:
  base-paths: [src]
```

`colcon list --paths-only`

> /opt/ros/master/src/ApexAI/performance_test/performance_test
> /opt/ros/master/src/ament/ament_cmake/ament_cmake
> ...

`colcon list --paths-only --paths src/ros2/rmw/rmw`

> /opt/ros/master/src/ApexAI/performance_test/performance_test
> /opt/ros/master/src/ament/ament_cmake/ament_cmake
> ...

` colcon list --paths-only --paths src/ros2/rmw/rmw --base-paths .`
> /opt/ros/master
> /opt/ros/master/src/ros2/rmw/rmw
(even though I have a top-level CMakeLists.txt in the current directory, this is unexpected)

`colcon list --paths-only --paths src/ros2/rmw/rmw --base-paths ""`
`colcon list --paths-only --paths src/ros2/rmw/rmw --base-paths ''`
`colcon list --paths-only --paths src/ros2/rmw/rmw --base-paths`
> /opt/ros/master/src/ros2/rmw/rmw

This is the expected result.

It seems that passing `--paths` on the command line should cause colcon to not recurse through base-paths in the yaml file. Better yet, have no special handling here and set the default '--paths' value to `"**"`

**Comment by dirk-thomas** [comment] 2020-01-07 05:21
Conceptionally the discovery extensions distinguish between the ones which have explicit parameters from extensions which only have a default value. At the moment the `default=...` value of `argparse` arguments can't be distinguished from arguments which have been explicitly passed through the CLI. That is why the recursive crawling (`--base-paths`) happens even though explicit paths are passed with `--paths`.

> It seems that passing `--paths` on the command line should cause colcon to not recurse through base-paths in the yaml file.

The solution to that problem is to be able to identify a default value independently from the actual value. Please see #288 and colcon/colcon-recursive-crawl#17 which add this for the discovery extensions. Additionally the `colcon-default` package needs to annotate the default values provided from a config file in the same way (see colcon/colcon-default#20).

Those changes together should provide the expected behavior. It would be great if you could give those patches a try and comment here with the result.

> Better yet, have no special handling here and set the default '--paths' value to "**"

The described approach wouldn't work since the expansion of the star(s) happens in the shell. Using two stars is the same as a single star and that only expands to the directories and files directly within the cwd. It doesn't provide any recursive crawling logic.

**Comment by dirk-thomas** [comment] 2020-01-08 22:33
Assuming the previously referenced PRs have resolved the problem described in this ticket I will go ahead and close it. Please feel free to continue commenting.

**Closed by dirk-thomas** 2020-01-08 22:33 UTC
Labels: enhancement
