### ISSUE TITLE
Doesn't support CATKIN install variables

### ISSUE THREAD

**Issue by purplefishies** [colcon/colcon-core#302] opened 2020-02-06 00:38 UTC
I have a catkin based package that has installation locations listed as follows

install(DIRECTORY include/ouster
  DESTINATION ${CATKIN_GLOBAL_INCLUDE_DESTINATION}
)

install(TARGETS ouster_client ouster_client_example
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)

When I run colcon build these variables aren't being set.

```
Starting >>> ouster_client
--- stderr: ouster_client                         
CMake Error at CMakeLists.txt:37 (install):
  install DIRECTORY given no DESTINATION!


CMake Error at CMakeLists.txt:41 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "ouster_client".
```

These are all variables that are defined by Catkin build / install.

**Comment by dirk-thomas** [comment] 2020-02-06 00:57
As you mentioned yourself these CMake variable are coming from `catkin` - not `colcon` - see [global](https://github.com/ros/catkin/blob/e6815417e373a002ec7900b2be27dc63a5a5e1bf/cmake/all.cmake#L176-L183) and [package specific](https://github.com/ros/catkin/blob/e6815417e373a002ec7900b2be27dc63a5a5e1bf/cmake/catkin_destinations.cmake#L45-L51) variables. As a consequence whatever is not working for you with these variables is very unlikely related to `colcon`.

You are claiming that you are having a catkin based package. Can you please share the complete `CMakeLists.txt` of that package. I would expect that you are either not calling `find_package(catkin REQUIRED)` or at least not do so in the right scope.

**Comment by purplefishies** [comment] 2020-02-06 19:21
```
cmake_minimum_required(VERSION 3.1.0)
project(ouster_ros)
include(../CMakeScripts/colcon_cmake_vars.cmake)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_FLAGS         "${CMAKE_CXX_FLAGS} -Wall -Wextra")
set(CMAKE_CXX_FLAGS_DEBUG   "-O0 -g")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")

find_package(PkgConfig REQUIRED)
pkg_check_modules(jsoncpp REQUIRED jsoncpp)

find_package(ouster_viz QUIET)
find_package(catkin REQUIRED COMPONENTS
  message_generation
  std_msgs
  sensor_msgs
  geometry_msgs
  pcl_ros
  pcl_conversions
  roscpp
  ouster_client
  tf2
  tf2_ros
  tf2_geometry_msgs
)

add_message_files(FILES PacketMsg.msg)
add_service_files(FILES OS1ConfigSrv.srv)
generate_messages(DEPENDENCIES std_msgs sensor_msgs geometry_msgs)

include_directories(
  include
  ${catkin_INCLUDE_DIRS}
)

catkin_package(
  INCLUDE_DIRS include
  LIBRARIES ouster_ros
  CATKIN_DEPENDS
    roscpp message_runtime pcl_ros
    std_msgs sensor_msgs geometry_msgs
    ouster_client ouster_viz
)

add_library(ouster_ros STATIC src/os1_ros.cpp)
target_link_libraries(ouster_ros ${catkin_LIBRARIES})
add_dependencies(ouster_ros ${PROJECT_NAME}_gencpp)

add_executable(os1_node src/os1_node.cpp)
target_link_libraries(os1_node ouster_ros ${catkin_LIBRARIES})
add_dependencies(os1_node ${PROJECT_NAME}_gencpp)

add_executable(os1_cloud_node src/os1_cloud_node.cpp)
target_link_libraries(os1_cloud_node ouster_ros ${catkin_LIBRARIES})
add_dependencies(os1_cloud_node ${PROJECT_NAME}_gencpp)

if(OUSTER_VIZ)
add_executable(viz_node src/viz_node.cpp)
target_link_libraries(viz_node ${catkin_LIBRARIES})
add_dependencies(viz_node ${PROJECT_NAME}_gencpp)
endif(OUSTER_VIZ)

add_executable(img_node src/img_node.cpp)
target_link_libraries(img_node ouster_ros ${catkin_LIBRARIES})
add_dependencies(img_node ${PROJECT_NAME}_gencpp)

if( OUSTER_VIZ )
install(TARGETS viz_node
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)
endif(OUSTER_VIZ)

install(TARGETS os1_node
                os1_cloud_node
                img_node
  ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
  RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}

)
install(FILES os1.launch DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
```
This is an augmented version of the CMakeLists.txt file coming from ouster's ouster_example repo ( github.com/ouster-lidar/ouster_example ) .  I'm working on a unified CMakeLists.txt file that will support catkin_tools, catkin_make , catkin_make_isolated and colcon. So far the other three work just fine but colcon fails claiming it doens't know about these variables.  My hack solution was to define them if they aren't defined already  ( see the include at the top ). I'd prefer to not have to do this.

If I don't use this line  
```
include(../CMakeScripts/colcon_cmake_vars.cmake)
``` 
, then I get errors saying that there's no ARCHIVE DESTINATION 

```
Starting >>> ouster_client
--- stderr: ouster_client                         
CMake Error at CMakeLists.txt:38 (install):
  install DIRECTORY given no DESTINATION!


CMake Error at CMakeLists.txt:42 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "ouster_client".


---
Failed   <<< ouster_client      [ Exited with code 1 ]

```

**Comment by dirk-thomas** [comment] 2020-02-06 21:24
I don't see anything wrong in your `CMakeLists.txt` file and unfortunately it isn't sufficient to reproduce the problem.

I tried the following minimal CMake code which shows that the variable is defined as expected (you will need a dummy `package.xml` file in order to build it):

```
cmake_minimum_required(VERSION 3.15)
project(foo)
find_package(catkin REQUIRED)
catkin_package()
message("CATKIN_PACKAGE_SHARE_DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}")
```

If you can't find the problem in your CMake code I would suggest you share a ready to build package somehow (which doesn't have any dependencies) which reproduces the problem.

**Comment by purplefishies** [comment] 2020-02-07 06:42
I tried out your CMakeLists.txt file and saw a different error
```
Starting >>> foo     
--- stderr: foo                         
CMake Error at CMakeLists.txt:3 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.


---
Failed   <<< foo	[ Exited with code 1 ]

Summary: 0 packages finished [5.53s]
  1 package failed: foo
  1 package had stderr output: foo

```

I probably am missing a key library that goes along with Colcon .

**Comment by dirk-thomas** [comment] 2020-02-07 16:09
As the error message states `catkin` can't be found. So you likely haven't sourced the setup file of any ROS distro before.

Since this is not a bug in `colcon` I will go ahead and close the issue. Please feel free to continue commenting on the closed ticket.

**Closed by dirk-thomas** 2020-02-07 16:09 UTC
Labels: question

**Comment by purplefishies** [comment] 2020-02-07 19:38
I have sourced the following files 
```
source ~/ros2_crystal/ros2-linux/local_setup.bash
```
and 
```
source ~/ros2_crystal/ros2-linux/setup.bash
```

**Comment by dirk-thomas** [comment] 2020-02-07 19:46
ROS 2 doesn't have a package named `catkin`. That only exists in ROS 1 distributions.

**Comment by purplefishies** [comment] 2020-02-07 19:48
> ROS 2 doesn't have a package named `catkin`. That only exists in ROS 1 distributions.

I thought colcon claims to build Ament and Catkin packages ?

**Comment by dirk-thomas** [comment] 2020-02-07 19:53
> I thought colcon claims to build Ament and Catkin packages ?

Yes, it does. You can use it to build a ROS 1 workspace as well as to build a ROS 2 workspace.

That doesn't mean that you can mix ROS 1 and ROS 2 packages in a single workspace though.

**Comment by purplefishies** [comment] 2020-02-07 20:04
1. I'm using your sample CMakeLists.txt file ( which had the **find_package(catkin REQUIRED)** line  ).

2. For testing I have no other files or projects in this workspace ( no mixing of ros1 or ros2 ). I want it to be purely ROS2.

3. My goal is to produce a project CMakeLists.txt file that is ROS1 / ROS2 agnostic for another company.  Ideally the same file could be built by either ROS. For my testing I'm just using ROS2 and colcon.

4. colcon, after sourcing the ~/ros2_crystal/ros2-linux/{local_setup.bash,setup.bash} does not seem to work due to not being able to find these preset variables. If I use this file
```
colcon_cmake_vars.cmake
```
which looks like 
```
...
if (NOT DEFINED CATKIN_GLOBAL_LIBEXEC_DESTINATION )
  set(CATKIN_GLOBAL_LIBEXEC_DESTINATION lib)
endif()

if (NOT DEFINED CATKIN_GLOBAL_SHARE_DESTINATION)
  set(CATKIN_GLOBAL_SHARE_DESTINATION share )
endif()

if ( NOT DEFINED CATKIN_PACKAGE_LIB_DESTINATION )
  set(CATKIN_PACKAGE_LIB_DESTINATION lib)
endif()
...
```
Then my colcon build and install work fine.

**Comment by dirk-thomas** [comment] 2020-02-07 20:46
> I'm using your sample CMakeLists.txt file ( which had the find_package(catkin REQUIRED) line ).

> For testing I have no other files or projects in this workspace ( no mixing of ros1 or ros2 ). I want it to be purely ROS2.

As said before, these two things don't go together. `catkin` doesn't exist in ROS 2. You can either use vanilla CMake or `find_package(ament_cmake REQUIRED)` (which is the counterpart to catkin in 
ROS 2).

> My goal is to produce a project CMakeLists.txt file that is ROS1 / ROS2 agnostic for another company. Ideally the same file could be built by either ROS. For my testing I'm just using ROS2 and colcon.

Then you should use vanilla CMake (and the build type `cmake` in the `package.xml` file) and neither `find_package` `catkin` nor `ament_cmake`.

**Comment by purplefishies** [comment] 2020-02-08 06:08
Thank you for the clarification .  Sincerely, Jimi
