### ISSUE TITLE
startup time is slow

### ISSUE THREAD

**Issue by alecGraves** [colcon/colcon-core#551] opened 2023-03-25 00:21 UTC
```
$ time colcon --help >> /dev/null

real    0m0.741s
user    0m0.238s
sys     0m0.095s
```

Compared to cmake:
```
$ time cmake --help >> /dev/null

real    0m0.007s
user    0m0.007s
sys     0m0.000s
```

or make:
```
$ time make --help >> /dev/null

real    0m0.001s
user    0m0.002s
sys     0m0.000s
```

And this is on some reasonable hardware:
```
$ time cat /proc/cpuinfo |  grep 'model name' | head -n1
model name      : 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

real    0m0.003s
user    0m0.005s
sys     0m0.000s
```

It would be good to focus on cli performance, especially for things like getting help messages. Some people try to write robot code on things like beagleboard or a raspberry pi.

**Comment by cottsay** [comment] 2023-03-25 00:23
Duplicate of #398

**Closed by cottsay** 2023-03-25 00:23 UTC
