### ISSUE TITLE
dev setup: needs explicit `wheel` dependency

### ISSUE THREAD

**Issue by dimaqq** [colcon/colcon-core#470] opened 2022-01-18 02:47 UTC
What I did:

```
python3.9 -m venv .env
. .env/bin/activate.fish  # or activate or activate.csh
python -m pip install -e .
```

The `EmPy` dependency initially hit an `error: invalid command 'bdist_wheel'`.
The dep actually did install via `setup.py` but it seems that in-place installation of `colcon-core` did not succeed because of that.
I ran the same `python -m pip install -e .` again and got 16x "already satisfied" followed by `Successfully installed colcon-core`.

I think there could be a quick fix of added the `wheel` dep locally 🤔

**Comment by cottsay** [comment] 2022-01-28 19:10
I don't think this is a problem in colcon, but rather in EmPy. I would anticipate that in your environment, you'd hit the same error if you replaced the last line with `python -m pip install EmPy`.

**Comment by dimaqq** [comment] 2022-03-02 02:19
that's totally possible.

**Comment by cottsay** [comment] 2022-05-05 19:58
I set up your reproducer locally, and I can see the issue. Indeed, invoking `python3 -m pip install EmPy` outside the context of colcon also produces the error, so this is not a bug in `colcon-core`.

**Comment by cottsay** [comment] 2024-06-10 19:35
There's nothing we can do in colcon to resolve the issue, so I'm closing this issue.

**Closed by cottsay** 2024-06-10 19:35 UTC
