### ISSUE TITLE
asyncio error messages after CancelledError with Python 3.5 / Ubuntu 16.04

### ISSUE THREAD

**Issue by dejanpan** [colcon/colcon-core#138] opened 2018-12-16 05:42 UTC
## Our environment
1. Ubuntu 16.04
1. ROS 2 Bouncy
1. colcon version-check
```
colcon-argcomplete 0.2.2: newer version available (0.2.3)
colcon-bash 0.3.1: up-to-date
colcon-cmake 0.2.4: up-to-date
colcon-core 0.3.13: newer version available (0.3.14)
colcon-defaults 0.2.1: up-to-date
colcon-devtools 0.2.1: up-to-date
colcon-lcov-result 0.2.0: up-to-date
colcon-library-path 0.2.0: up-to-date
colcon-metadata 0.2.1: up-to-date
colcon-mixin 0.1.0: newer version available (0.1.1)
colcon-notification 0.2.5: up-to-date
colcon-output 0.2.3: up-to-date
colcon-package-information 0.2.1: up-to-date
colcon-package-selection 0.2.1: up-to-date
colcon-parallel-executor 0.2.2: up-to-date
colcon-pkg-config 0.1.0: up-to-date
colcon-powershell 0.3.3: up-to-date
colcon-python-setup-py 0.2.1: up-to-date
colcon-recursive-crawl 0.2.0: up-to-date
colcon-ros 0.3.5: up-to-date
colcon-test-result 0.3.0: up-to-date
colcon-zsh 0.3.1: up-to-date
```
3. build command: `colcon build --merge-install`

After we had a code error like this: 
```sh
error: ‘m_pcl_sub’ was not declared in this scope
     const auto & loaned_message = m_pcl_sub->take();
```

colcon printed out a whole bunch of errors:

```
Starting >>> euclidean_cluster                                                                                
--- stderr: apex_tf                                                                                           
/home/user/1816/apex_ws/src/apex_app/common/apex_tf/src/local_tf.cpp: In member function ‘virtual void apex_app::common::apex_tf::LocalTf::TfSubTask::task_function()’:
/home/user/1816/apex_ws/src/apex_app/common/apex_tf/src/local_tf.cpp:142:35: error: ‘m_pcl_sub’ was not declared in this scope
     const auto & loaned_message = m_pcl_sub->take();
                                   ^
make[2]: *** [CMakeFiles/apex_tf.dir/src/local_tf.cpp.o] Error 1
make[1]: *** [CMakeFiles/apex_tf.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< apex_tf	[ Exited with code 2 ]
Finished <<< lifecycle [9.53s]                                                                
Aborted  <<< velodyne_driver
Aborted  <<< euclidean_cluster
Aborted  <<< lidar_integration
Aborted  <<< motion_model
Aborted  <<< performance_test
Aborted  <<< udp_driver

Summary: 169 packages finished [1min 52s]
  1 package failed: apex_tf
  6 packages aborted: euclidean_cluster lidar_integration motion_model performance_test udp_driver velodyne_driver
  1 package had stderr output: apex_tf
  25 packages not processed
[116.165s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeed4a9e8 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[116.166s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeed4a128 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[118.025s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeee97198 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[118.026s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeed1bfd0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[118.026s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeeb2fbe0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[118.027s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeeb2f780 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[118.869s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeeaf1518 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[118.869s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeeaf1a58 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[138.736s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeead00f0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[138.737s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f7aeead09e8 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[138.754s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.755s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[138.756s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
```

Google search didn't turn out anything similar. Any idea where to start digging?

**Comment by dirk-thomas** [comment] 2018-12-16 12:33
The stacktraces are coming from an unclean shutdown of asyncio tasks. Since these can be very timing specific can you please share exact steps for a reproducible example.

**Comment by deeplearningrobotics** [comment] 2018-12-26 17:00
@dirk-thomas: It happens with every build that has a build error so it is not spurious.  I can try to reproduce it with the ROS 2 master codebase.

**Comment by dirk-thomas** [comment] 2018-12-26 17:07
@deeplearningrobotics I doesn't happen for me on Ubuntu 18.04. So I need a reproducible example in order to be able to investigate it. I would expect the packages in the workspace to be unrelated to this (except that obviously one needs to fail in order for the packages processed in parallel to be aborted).

**Comment by dirk-thomas** [comment] 2019-01-17 00:48
@deeplearningrobotics Did you have a change to come up with a reproducible example for this?

**Comment by dirk-thomas** [comment] 2019-01-22 18:18
I will go ahead and close this ticket for now. Please feel free to comment with the requested information and the ticket can be reopened.

**Comment by dejanpan** [comment] 2019-01-22 19:05
@dirk-thomas I have a mini reproducer:

```sh
cd
mkdir ndt_ws/src
cd ndt_ws/src
git clone https://github.com/dejanpan/ndt_matching.git
cp -R ndt_matching ndt_matching2
sed -i -e 's/rclcpp::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr sub2_;/\/\/rclcpp::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr sub2_;/g' ndt_matching/src/ndt_node.cpp 
cd ndt_matching2
sed -i -e 's/ndt_matching/ndt_matching2/g' package.xml 
sed -i -e 's/ndt_matching/ndt_matching2/g' CMakeLists.txt
cd ../..
colcon build --merge-install
```

It should result in an error like this (only on the FIRST build):
```sh
colcon build --merge-install
Starting >>> ndt_matching
Starting >>> ndt_matching2
--- stderr: ndt_matching                                                                          
/home/dejan.pangercic/ndt_ws/src/ndt_matching/src/ndt_node.cpp: In constructor ‘Listener::Listener(const string&, const string&)’:
/home/dejan.pangercic/ndt_ws/src/ndt_matching/src/ndt_node.cpp:51:5: error: ‘sub2_’ was not declared in this scope
     sub2_ = create_subscription<sensor_msgs::msg::PointCloud2>(topic_name2, callback2);
     ^
make[2]: *** [CMakeFiles/ndt_node.dir/src/ndt_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/ndt_node.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< ndt_matching	[ Exited with code 2 ]
Aborted  <<< ndt_matching2

Summary: 0 packages finished [3.47s]
  1 package failed: ndt_matching
  1 package aborted: ndt_matching2
  1 package had stderr output: ndt_matching
[5.951s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7fb417ab7b38 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[5.952s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7fb417ab7978 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[5.966s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[5.967s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /usr/local/lib/python3.5/dist-packages/colcon_core/subprocess.py:220> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
```

**Comment by dejanpan** [comment] 2019-01-22 19:11
@dirk-thomas I updated above comment with:  
Update: I can not re-produce below on Ubuntu 18.04. On Ubuntu 16.04 it fails every time.

**Comment by dirk-thomas** [comment] 2019-01-22 23:36
I can reproduce the error messages on Ubuntu 16.04 / Python 3.5.

The `asyncio` error messages appear after the invocation has finished and shouldn't affect the behavior / outcome of the invocation. Since the problem exists only with Python 3.5 this might be a problem within `asyncio` itself.

The code running the coroutines mentioned in the error messages (`_fd2callback`) is correctly finishing all of them, see: https://github.com/colcon/colcon-core/blob/ccf68192a79f4f41a385c9d19cf090d79e49f05f/colcon_core/subprocess.py#L179-L184

I will keep this ticket open but I don't expect that I will be able to come up with a patch for it. Hence I assigned the label "help wanted". I am more than happy to review contributed patches which improve the ugly output.

**Comment by mikepurvis** [comment] 2019-10-30 18:08
I confirm seeing this as well on 16.04— it happens on failure, and there's a variation of it when I ctrl-c out of a running build as well:

```
Aborted  <<< gtsam
[54.978s] ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<_fd2callback() done, defined at /home/administrator/colcon_env/lib/python3.5/site-packages/colcon_core/subprocess.py:216> exception=RuntimeError('cannot reuse already awaited coroutine',)>
Traceback (most recent call last):
  File "/home/administrator/colcon_env/lib/python3.5/site-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
RuntimeError: cannot reuse already awaited coroutine
[54.980s] ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<_fd2callback() done, defined at /home/administrator/colcon_env/lib/python3.5/site-packages/colcon_core/subprocess.py:216> exception=RuntimeError('cannot reuse already awaited coroutine',)>
Traceback (most recent call last):
  File "/home/administrator/colcon_env/lib/python3.5/site-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
RuntimeError: cannot reuse already awaited coroutine
[54.993s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f5a5e55e710 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[54.994s] ERROR:concurrent.futures:exception calling callback for <Future at 0x7f5a5e55eb00 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Summary: 2 packages finished [54.5s]
4 packages aborted: ...
3 packages had stderr output: ...
nnn packages not processed
[55.204s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /home/administrator/colcon_env/lib/python3.5/site-packages/colcon_core/subprocess.py:216> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
[55.205s] ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<_fd2callback() done, defined at /home/administrator/colcon_env/lib/python3.5/site-packages/colcon_core/subprocess.py:216> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:414]>
```

The situation is slightly better if I use colcon from a py3.8 venv (deadsnakes), but still lots of spurious output, including a similar warning about the event loop being closed (and needing to issue a final ctrl-c as well):

```
Failed   <<< rosmaster  [ Exited with code 1 ]
--- stderr: std_msgs
Traceback (most recent call last):
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_core/subprocess.py", line 176, in _async_check_call
    done, _ = await asyncio.wait(callbacks, return_when=ALL_COMPLETED)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 426, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 523, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_core/task/__init__.py", line 92, in __call__
    return await task_method(*args, **kwargs)
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_ros/task/catkin/build.py", line 72, in build
    rc = await extension.build(
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_cmake/task/cmake/build.py", line 85, in build
    rc = await self._reconfigure(args, env)
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_cmake/task/cmake/build.py", line 172, in _reconfigure
    return await check_call(
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_core/task/__init__.py", line 147, in check_call
    rc = await run(
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_core/subprocess.py", line 81, in run
    rc, _, _ = await _async_check_call(
  File "/home/administrator/colcon_env/lib/python3.8/site-packages/colcon_core/subprocess.py", line 183, in _async_check_call
    for task in done:
UnboundLocalError: local variable 'done' referenced before assignment
---
Failed   <<< std_msgs   [ Exited with code 1 ]

Summary: 16 packages finished [1min 21s]
  4 packages failed: gtsam rosmaster std_msgs xmlrpcpp
  5 packages had stderr output: aruco gtsam rosmaster std_msgs xmlrpcpp
  654 packages not processed
[81.366s] WARNING:asyncio:Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 31742 is closed

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by dirk-thomas** [comment] 2019-10-31 02:40
> The situation is slightly better if I use colcon from a py3.8 venv (deadsnakes), but still lots of spurious output, including a similar warning about the event loop being closed (and needing to issue a final ctrl-c as well):

Does that happen all the time for you or only sometimes? Do you happen to have reproducible steps?

> `UnboundLocalError: local variable 'done' referenced before assignment`

You might want to give #245 a try which should resolve this problem.

**Comment by dirk-thomas** [comment] 2019-11-03 05:04
I will only be able to look into it when it is reproducible on 18.04 (or soon also 20.04) with the default Python interpreter. Don't because other environments are not something we use / test with.

**Comment by mikepurvis** [comment] 2019-11-04 18:14
No worries! We probably won't be looking into it either— this just clarifies for us that a colcon migration is not in the cards for us until we're no longer targeting 16.04.

**Comment by dirk-thomas** [comment] 2020-01-06 17:47
@mikepurvis It might be worth to try this case again with recent changes landed which addressed some problems around the `CancelledError` handling (see #284 and #285).

**Comment by dirk-thomas** [comment] 2020-02-19 06:15
@mikepurvis Friendly ping.

**Comment by mikepurvis** [comment] 2020-02-19 14:31
Yup, just re-tested now and the issue on 16.04 is now fixed. Thanks!

**Closed** 2020-02-19 15:12 UTC
Labels: bug, help wanted
